apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      initContainers:
        - name: db-migration
          image: roarceus/db-webapp:latest
          env:
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: DB_URL 
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: FLYWAY_LOCATIONS
              value: "filesystem:/flyway/sql/"
            - name: FLYWAY_SCHEMAS
              value: "webapp"
          args: ["migrate"]
      containers:
        - name: webapp
          image: roarceus/webapp-hello-world:latest
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: DB_NAME
          ports:
            - containerPort: 8080
